---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - redis.redis.operator.io
  resources:
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.operator.io
  resources:
  - redissentinels/finalizers
  verbs:
  - update
- apiGroups:
  - redis.redis.operator.io
  resources:
  - redissentinels/status
  verbs:
  - get
  - patch
  - update
