apiVersion: redis.redis.operator.io/v1
kind: RedisSentinel
metadata:
  labels:
    app.kubernetes.io/name: redis-sentinel-operator
    app.kubernetes.io/managed-by: kustomize
  name: redissentinel-sample
spec:
  # TODO(user): Add fields here
